apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-nginx
        image: nginx
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: cipapp
spec:
  type: ClusterIP  ## this is default if we do not type in service definition
  selector:
    app: myapp
  ports:
   - protocol: TCP
     port: 800
     targetPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment1
  labels:
    app: myapp1
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: kubeserve
        image: leaddevops/kubeserve:v1
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: cipapp1
spec:
  type: ClusterIP  ## this is default if we do not type in service definition
  selector:
    app: myapp1
  ports:
   - protocol: TCP
     port: 700
     targetPort: 80